---
- name: Create MongoDB Superuser without replset
  mongodb_user:
    database: 'admin'
    name: '{{ mongod_sa_user }}'
    password: '{{ mongod_sa_pass }}'
    roles: userAdminAnyDatabase
    state: present
  no_log: true
  when: ( mongod_replset is not defined ) or ( mongod_replset == 'Non-ReplicaSet' )

- name: Create MongoDB Superuser with replset
  mongodb_user:
    replica_set: '{{ mongod_replset | upper }}'
    database: 'admin'
    name: '{{ mongod_sa_user }}'
    password: '{{ mongod_sa_pass }}'
    roles: 'root'
    state: 'present'
  no_log: true
  when:
    - mongod_replset is defined
    - mongod_replset != 'Non-ReplicaSet'
    - mongod_servers[0] in ansible_default_ipv4.address

- name: Ensure authentication is enabled for MongoDB
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    insertafter: 'security:'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^  authorization:', line: '  authorization: enabled' }

- name: MongoDB authentication Keyfiles transfer
  template:
    src: 'authentication.key.j2'
    dest: '{{ mongod_path }}/mongod/authentication.key'
    owner: 'mongod'
    group: 'mongod'
    mode: 0600
  no_log: true
  when:
    - mongod_replset is defined
    - mongod_replset != 'Non-ReplicaSet'

- name: Ensure authentication is enabled for MongoDB
  lineinfile:
    state: present
    dest: /etc/mongod.conf
    insertafter: 'security:'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^  keyFile:', line: '  keyFile: {{ mongod_path }}/mongod/authentication.key' }
  when:
    - mongod_replset is defined
    - mongod_replset != 'Non-ReplicaSet'

- name: Ensure MongoDB service is reload
  systemd:
    name: 'mongod.service'
    state: restarted
