---
- name: Create MongoDB business database with replset
  mongodb_user:
    replica_set: '{{ mongod_replset | upper }}'
    login_user: '{{ mongod_sa_user }}'
    login_password: '{{ mongod_sa_pass }}'
    login_host: '{{ ansible_default_ipv4.address }}'
    login_port: '{{ mongod_port }}'
    ssl: '{{ mongod_ssl | bool and mongod_authorization | bool }}'
    ssl_cert_reqs: 'CERT_NONE'
    database: '{{ item.dbs | upper}}'
    name: '{{ item.user }}'
    password: '{{ item.pass }}'
    roles: '{{ item.role }}'
    state: 'present'
  loop: '{{ mongod_bu_dbs_arg }}'
  when:
    - mongod_replset is defined
    - mongod_replset != 'Non-ReplicaSet'
    - mongod_servers[0] in ansible_default_ipv4.address
  no_log: true

- name: Create MongoDB business database without replset
  mongodb_user:
    login_user: '{{ mongod_sa_user }}'
    login_password: '{{ mongod_sa_pass }}'
    login_host: '{{ ansible_default_ipv4.address }}'
    login_port: '{{ mongod_port }}'
    ssl: '{{ mongod_ssl | bool and mongod_authorization | bool }}'
    ssl_cert_reqs: 'CERT_NONE'
    database: '{{ item.dbs | upper }}'
    name: '{{ item.user }}'
    password: '{{ item.pass }}'
    roles: '{{ item.role }}'
    state: 'present'
  loop: '{{ mongod_bu_dbs_arg }}'
  when: ( mongod_replset is not defined ) or ( mongod_replset == 'Non-ReplicaSet' )
  no_log: true
