---
- name: Prometheus user password generator
  set_fact:
    mongodb_exporter_user_passwd: "{{ lookup('password', '' + group_names[-1] + ':exporter length=12 chars=ascii_letters,digits') }}"

- name: Create mongodb_exporter user with replset
  mongodb_user:
    replica_set: '{{ mongod_replset | upper }}'
    database: 'admin'
    name: 'prometheus'
    password: '{{ mongodb_exporter_user_passwd }}'
    login_host: '{{ ansible_default_ipv4.address }}'
    login_port: '{{ mongod_port }}'
    state: 'present'
    roles:
      - db: admin
        role: clusterMonitor
      - db: local
        role: read
  when:
    - mongod_replset is defined
    - mongod_replset != 'Non-ReplicaSet'
    - mongod_servers[0] in ansible_default_ipv4.address
  no_log: true

- name: Create mongodb_exporter user without replset
  mongodb_user:
    database: 'admin'
    name: 'prometheus'
    password: '{{ mongodb_exporter_user_passwd }}'
    login_host: '{{ ansible_default_ipv4.address }}'
    login_port: '{{ mongod_port }}'
    state: 'present'
    roles:
      - db: admin
        role: clusterMonitor
      - db: local
        role: read
  when: ( mongod_replset is not defined ) or ( mongod_replset == 'Non-ReplicaSet' )
  no_log: true

- name: mongodb_exporter config file transfer
  template:
    src: 'mongodb_exporter.j2'
    dest: '/etc/default/mongod_exporter'
    owner: 'root'
    group: 'root'
    mode: '0640'
  no_log: true
  register: mongodb_exporter_conf

- name : mongodb_exporter systemd file transfer
  copy:
    src: 'mongodb_exporter.service'
    dest: '/lib/systemd/system/mongodb_exporter.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: mongodb_exporter_systemd

- name: Ensure mongod_exporter service is enabled
  systemd:
    name: 'mongodb_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0
  when: mongodb_exporter_conf is changed or mongodb_exporter_systemd is changed
