---
- name: Allow MongoDB service port
  firewalld:
    port: '{{ item }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop:
   - '{{ mongod_port }}'
   - '{{ mongod_exporter_port }}'
