---
- name: Creating MongoDB folder
  file:
    dest: '{{ mongod_path }}/mongod'
    state: 'directory'
    owner: 'mongod'
    group: 'mongod'
    mode: '0750'

- name: Configure kernel parameters
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: 'yes'
    sysctl_set: 'yes'
    sysctl_file: '/etc/sysctl.d/20-sysctl.conf'
  loop: '{{ mongod_kernel_parameters }}'

- name: MongoDB Configure & Scripts file transfer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: 'yes'
    owner: '{{ item.owner }}'
    group: '{{ item.owner }}'
    mode: '{{ item.mode }}'
  loop: '{{ mongod_conf_scripts }}'

- name: Ensure MongoDB service is enabled
  systemd:
    name: 'mongod.service'
    enabled: 'yes'
    state: 'started'
    daemon_reload: 'yes'
