---
- name: Gather MongoDB node variables for replication
  set_fact:
    mongod_servers: "\
      {% set _mongod_servers = [] %}\
      {% for host in groups[group_names[-1]] %}\
      {% set _mongod_replset = mongod_replset | default('', true) %}\
      {% set _mongod_node_role = mongod_node_role | default('', true) %}\
        {% if ( _mongod_replset == mongod_replset and (_mongod_node_role == 'arbiter' or _mongod_node_role == 'replica')) %}\
          {% if _mongod_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
        {% endif %}\
      {% endfor %}\
      {{ _mongod_servers }}"
  when:
    - mongod_replset != 'Non-ReplicaSet'
    - mongod_replset is defined
    - mongod_servers is not defined or mongod_servers | length < 1

- name: Check if MongoDB tablespace exists
  stat:
    path: '{{ mongod_path }}/mongod/diagnostic.data'
  register: result

- name: Mongo operation
  block:
    - name: Include tasks for specific OS
      include: '{{ ansible_os_family }}.yml'
    - name: Include firewall tasks
      include: 'firewall.yml'
    - name: Straight to getenforce selinux status
      include: 'selinux.yml'
    - name: Install requirement python package
      pip:
        name: '{{ mongod_python_dependent_packages }}'
        state: 'forcereinstall'
        extra_args: '--default-timeout=120 --ignore-installed -i https://{{ mongod_pypi_url }}/simple --trusted-host {{ mongod_pypi_url }}'
      register: mongod_python_status
      until: mongod_python_status is succeeded
      retries: 5
      delay: 2
    - name: Include initialization tasks
      include: 'initialization.yml'
    - name: Include replica sets tasks
      include: 'replset.yml'
      when:
        - mongod_replset is defined
        - mongod_replset != 'Non-ReplicaSet'
        - mongod_servers[0] in ansible_default_ipv4.address
    - name: Include backup tasks
      include: 'backup.yml'
    - name: Include prometheus exporter tasks
      include: 'exporter.yml'
      when: exporter_is_install | bool
    - name: Include authentication tasks
      include: 'authentication.yml'
      when: mongod_authorization | bool
    - name: Include business database tasks
      include: 'database.yml'
      when:
        - mongod_bu_dbs_arg is defined
        - mongod_authorization | bool
  when:
    - not result.stat.exists
    - ( mongod_replset is not defined ) or (mongod_replset == 'Non-ReplicaSet') or (( mongod_replset is defined ) and ( mongod_replset != 'Non-ReplicaSet' ) and ( mongod_servers|length is not divisibleby 2 ) and ( mongod_servers|length > 2 ))

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
    - ( mongod_replset is not defined ) or (mongod_replset == 'Non-ReplicaSet') or (( mongod_replset is defined ) and ( mongod_replset != 'Non-ReplicaSet' ) and ( mongod_servers|length is not divisibleby 2 ) and ( mongod_servers|length > 2 ))

- name: Replica Set Members check
  debug:
    msg: 
      - 'The minimum recommended configuration for a ReplicaSet is 3 member, now is {{ mongod_servers|length }}.'
      - 'The recommended configuration for a ReplicaSet members is odd, now is {% if mongod_servers|length is divisibleby 2 %}even{% else %}odd{% endif %}.'
      - 'Task skipped completely.'
  when:
    - mongod_replset is defined
    - mongod_replset != 'Non-ReplicaSet'
    - mongod_servers|length is divisibleby 2
    - mongod_servers|length <= 2
  run_once: true
