---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add MongoDB YUM repositories
  yum_repository:
    name: '{{ mongod_repo_name }}'
    description: '{{ mongod_repo_name }} YUM repository'
    file: '{{ mongod_repo_name }}'
    baseurl: '{{ mongod_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the MongoDB packages
  yum:
    name: '{{ mongod_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5