---
- name: Add MongoDB YUM repositories
  yum_repository:
    name: '{{ mongod_repo_name }}'
    description: '{{ mongod_repo_name }} YUM repository'
    file: '{{ mongod_repo_name }}'
    baseurl: '{{ mongod_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the MongoDB packages
  yum:
    name: '{{ item }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ mongod_packages|flatten(levels=1) }}'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5