---
- name: Add MongoDB YUM repositories
  yum_repository:
    name: '{{ mongo_repo_name }}'
    description: '{{ mongo_repo_name }} YUM repository'
    file: '{{ mongo_repo_name }}'
    baseurl: '{{ mongo_repo_url }}'
    gpgcheck: no

- name: Install the MongoDB packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ mongo_packages }}'