---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add EPEL YUM repositories.
  yum_repository:
    name: '{{ mongod_epel_repo_name }}'
    description: '{{ mongod_epel_repo_name }} YUM repo'
    file: '{{ mongod_epel_repo_name }}'
    baseurl: '{{ mongod_epel_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'
  when:
    - mongod_backupset_arg.cloud_rsync | bool
    - mongod_backupset_arg.cloud_drive is defined

- name: Install the Rclone command line program packages.
  yum:
    name: 'rclone'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
    update_cache: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5
  when:
    - mongod_backupset_arg.cloud_rsync | bool
    - mongod_backupset_arg.cloud_drive is defined

- name: Add MongoDB YUM repositories
  yum_repository:
    name: '{{ mongod_repo_name }}'
    description: '{{ mongod_repo_name }} YUM repository'
    file: '{{ mongod_repo_name }}'
    baseurl: '{{ mongod_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the MongoDB packages
  yum:
    name: '{{ mongod_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5
