---
- name: Add MongoDB YUM repositories
  yum_repository:
    name: '{{ mongod_repo_name }}'
    description: '{{ mongod_repo_name }} YUM repository'
    file: '{{ mongod_repo_name }}'
    baseurl: '{{ mongod_repo_url }}'
    gpgcheck: no

- name: Install the MongoDB packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ mongod_packages }}'