---
- name: Register exporter service with an http health check
  uri:
    url: 'http://{{ item }}:{{ consul_http_port }}/v1/agent/service/register'
    method: 'PUT'
    headers:
      X-Consul-Token: "{{ consul_exporter_token }}"
    body: '{"ID":"{{ inventory_hostname | upper }}_mongodb_exporter","name":"mongodb_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ mongo_port_arg.mongodb_exporter }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ mongo_port_arg.mongodb_exporter }}/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"5s"}]}'
    body_format: 'json'
  environment:
    no_proxy: '{{ item }}'
  with_items: '{{ consul_clients }}'
  when: consul_is_register
  no_log: true