---
- name: MongoDB replication configuration
  mongodb_replication:
    login_host: '{{ ansible_default_ipv4.address }}'
    login_port: '{{ mongod_port }}'
    replica_set: '{{ mongod_replset | upper }}'
    host_name: '{{ item }}'
    host_port: '{{ mongod_port }}'
    host_type: '{{ mongod_node_role }}'
    priority: '2.0'
  loop: '{{ mongod_servers }}'
